In [2]:
import numpy as np

In [ ]:
F = np.random.rand()
D = np.random.rand(3)

print('F: {}\n'.format(F))
print('D: {}\n'.format(D))


F: 0.5466021888062896

D: [0.65430677 0.22239291 0.69000069]



In [ ]:
ndarray = np.array([[1,2],[3,4],[5,6]])
print(ndarray)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
ndarray = np.array([1, 2, 3])
print(ndarray)

[1 2 3]


#⑧

In [ ]:
np. arange(0,5,2)

array([0, 2, 4])

In [ ]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

#⑨


In [ ]:
ND = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ED_ND = np.expand_dims(ND, axis=0)
ED_ND.shape


(1, 3, 3)

In [3]:
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)

[[ 1.94693666 -1.67424138 -1.95447377 -0.16846701 -0.56685223]
 [-1.19647043  0.61136457 -0.46995168 -0.24994833  0.66319143]
 [ 2.20705575 -0.99649275 -0.64986275  0.48643076  1.05503265]
 [ 1.01258817 -0.42169775 -1.61222587 -0.93039545  1.91827949]
 [ 1.29648042 -1.11693092  0.90910952 -0.278619   -1.02256756]]
